name: Spring Build With Gradle

on:
  push:
    branches: [main, release, develop]
  pull_request:
    branches: [main, release, develop]

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "**/build/test-results/**/*.xml"

      - name: Upload JAR Artifact
        if: success() && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          # docker-build-push.yml의 이름과 일치해야함.
          name: app-jar-${{ github.sha }}
          path: build/libs/pray-together-0.0.1-SNAPSHOT.jar
          retention-days: 1 # 아티팩트 보관 기간 1일


      - name: Trigger Docker workflow
        if: success() && github.event_name == 'push'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: trigger-docker-workflow
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'